const language = [
    { id: 1, name: 'English', code: 'en-US' },
    { id: 2, name: '中文', code: 'zh-CN' },
    { id: 3, name: '日本語', code: 'ja-JP' },
    { id: 4, name: '한국어', code: 'ko-KR' },
    { id: 5, name: 'Deutsch', code: 'de-DE' },
    { id: 6, name: 'Français', code: 'fr-FR' },
    { id: 7, name: 'Italiano', code: 'it-IT' },
    { id: 8, name: 'Español', code: 'es-ES' },
    { id: 9, name: 'Português', code: 'pt-PT' },
    { id: 10, name: 'Русский', code: 'ru-RU' },
    { id: 11, name: 'العربية', code: 'ar-SA' },
    { id: 12, name: 'हिन्दी', code: 'hi-IN' },
    { id: 13, name: 'বাংলা', code: 'bn-BD' },
    { id: 14, name: 'Türkçe', code: 'tr-TR' },
    { id: 15, name: 'Tiếng Việt', code: 'vi-VN' },
    { id: 16, name: 'Bahasa Indonesia', code: 'id-ID' },
    { id: 17, name: 'ไทย', code: 'th-TH' },
    { id: 18, name: 'فارسی', code: 'fa-IR' },
    {id: 19, name: 'עברית', code: 'he-IL' },
    {id: 20, name: 'Nederlands', code: 'nl-NL' },
    {id: 21, name: 'Polski', code: 'pl-PL' },
    {id: 22, name: 'Svenska', code: 'sv-SE' },
    {id: 23, name: 'Magyar', code: 'hu-HU' },
    {id: 24, name: 'Čeština', code: 'cs-CZ' },
    {id: 25, name: 'Română', code: 'ro-RO' },
    {id: 26, name: 'Slovenčina', code: 'sk-SK' },
    {id: 27, name: 'Hrvatski', code: 'hr-HR' },
    {id: 28, name: 'Български', code: 'bg-BG' },
    {id: 29, name: 'Українська', code: 'uk-UA' },
    {id: 30, name: 'Suomi', code: 'fi-FI' },
    {id: 31, name: 'Dansk', code: 'da-DK' },
    {id: 32, name: 'Norsk', code: 'nb-NO' },
    {id: 33, name: 'Català', code: 'ca-ES' },
    {id: 34, name: '한국어', code: 'ko-KR' },
    {id: 35, name: '中文', code: 'zh-CN' },
    {id: 36, name: '日本語', code: 'ja-JP' },
    {id: 37, name: 'Deutsch', code: 'de-DE' },
    {id: 38, name: 'Français', code: 'fr-FR' },
    {id: 39, name: 'Italiano', code: 'it-IT' },
    {id: 40, name: 'Español', code: 'es-ES' },
    {id: 41, name: 'Português', code: 'pt-PT' },
    {id: 42, name: 'Русский', code: 'ru-RU' },
    {id: 43, name: 'العربية', code: 'ar-SA' },
    {id : 44, name : 'Nepali', code : 'ne-NP'},
    {id : 45, name : 'Romanized Nepali', code : 'ne-NP-x-romanized'},
    {id : 46, name : 'Hinglish', code : 'hi-IN-x-hinglish'}
  ];

  export default language;